apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # 读写权限，但同时只能被一个节点写入
  hostPath:
    path: "/mnt/data"