apiVersion: v1

# 以环境变量方式导入secret到Pod
kind: Pod
metadata:
  name: use-secret-env
spec:
  containers:
    - name: use-secret-env
      imagePullPolicy: IfNotPresent
      image: nginx
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
