kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-volume
  namespace: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/temp/data/jenkins"