spring:
  profiles:
    active: hello
  datasource:
    url: jdbc:mysql://192.168.52.111:3306/springbatch
    username: root
    password: 123456
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  batch:
    initialize-schema: always