version: "3"
services:
  mysql-server:
    image: mysql/mysql-server:8.0
    container_name: mysql-server
    hostname: mysql-server
    networks:
      - seata-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_AUTH_PLUGIN=mysql_native_password # 支持使用密码验证，mysql8.0默认不支持密码验证
    ports:
      - "3306:3306"
    volumes:
      - .conf/init-db:/docker-entrypoint-initdb.d
      - .runtime/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  nacos-server:
    image: nacos/nacos-server:v2.3.1-slim
    container_name: nacos-server-standalone
    hostname: nacos-server
    networks:
      - seata-network
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql-server
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ./.runtime/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql-server:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nacos-server:8848/nacos"]
      interval: 10s
      timeout: 5s
      retries: 3
  seata-server:
    image: seataio/seata-server:2.0.0-slim
    hostname: seata-server
    networks:
      - seata-network
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      # Seata Server 1.5.0版本开始，配置文件改为application.yml
      - .conf/seata-resources/application.yml:/seata-server/resources/application.yml
    expose:
      - 8091
      - 7091
    depends_on:
      nacos-server:
        condition: service_healthy
networks:
  seata-network: