# 参考：https://github.com/containerd/containerd/blob/main/docs/getting-started.md
  
---
- name: "Get Containerd"
  environment: "{{ proxy_env }}"
  ansible.builtin.unarchive:
    src: "https://github.com/containerd/containerd/releases/download/v{{ containerd_release_version }}/containerd-{{ containerd_release_version }}-linux-arm64.tar.gz"
    dest: "/usr/local"
    remote_src: yes
- name: "Make sure Containerd Service Dir Exist"
  ansible.builtin.file:
    state: directory
    path: "/usr/local/lib/systemd/system/"
- name: "Register Containerd Service"
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: "/usr/local/lib/systemd/system/containerd.service"
- name: "Enable Containerd Service"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "containerd"
    state: started
    enabled: true
- name: "Make sure Containerd config path Exist"
  ansible.builtin.file:
    path: "/etc/containerd/"
    state: directory
- name: "Containerd config"
  ansible.builtin.shell:
    containerd config default | sudo tee /etc/containerd/config.toml
- name: "Use systemd cgroup"
  ansible.builtin.shell:
    sed  -i "s/SystemdCgroup\s=\sfalse/SystemdCgroup = true/g" /etc/containerd/config.toml
- name: "Containerd Restart"
  ansible.builtin.systemd:
    name: containerd
    state: restarted