server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: git@github.com:xf616510229/repo.git
          # Git仓库账号
          username: 
          # Git仓库密码
          password:
            
  