version: '3.9'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activiti
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
